[[services]]
  name = "panel"

  [services.variables]
    ADMIN_USERNAME = "se7oadmin"
    ADMIN_PASSWORD = "Test1234"
    SECRET_KEY = "se7o-railway-secret-key-2026-randomxyz"
    MTPROXY_ENABLED = "true"
    MTPROXY_PORT = "443"

  [services.deploy]
    startCommand = "python main.py"
    healthcheckPath = "/health"
    healthcheckTimeout = 100
